# Generated by Django 5.2.4 on 2025-07-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default='Cart', on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
